{% set name = "unstructured" %}
{% set version = "0.15.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unstructured-{{ version }}.tar.gz
  sha256: f0f2c83a86d754df79b17f40c01a446c6f38ded4c253d1da1c2c0ec22f6ffc37
  patches:
    - setup.patch

build:
  # langdetect not available on py312
  skip: true  # [py<39 or py>311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - psutil
    - python
    - backoff
    - beautifulsoup4
    - certifi >=2023.7.22
    - chardet
    - charset-normalizer >=3.2.0
    - click >=8.1.7
    - dataclasses-json >=0.6.4
    - emoji
    - filetype
    - idna >=3.4
    - joblib >=1.4.2
    - jsonpath-python >=1.0.6
    - langdetect
    - lxml
    - marshmallow >=3.19.0
    - mypy_extensions >=1.0.0
    - nltk
    # NOTE(upstream) - numpy pin is because ONNX model weights are only compatible
    # with numpy 1.x.x
    - numpy <2
    - packaging >=23.1
    - python-dateutil >=2.8.2
    - python-iso639
    - python-magic
    - rapidfuzz
    - regex >=2023.12.25
    - requests >=2.31.0
    - six >=1.16.0
    - soupsieve >=2.5
    - tabulate
    - tqdm
    - typing-extensions >=4.7.1
    - typing_inspect >=0.9.0
    - unstructured-client >=0.15.1
    - urllib3 >=1.26.18
    - wrapt
    - deepdiff >=6.0
    - httpx >=0.27.0
    - nest-asyncio >=1.6.0
    - pypdf >=4.0
    - requests-toolbelt >=1.0.0

test:
  imports:
    - unstructured
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://unstructured.io
  license: Apache-2.0
  license_file: LICENSE.md
  license_family: Apache
  summary: A library that prepares raw documents for downstream ML tasks.
  description: |
    Unstructured provides a platform and tools to ingest and process
    unstructured documents for Retrieval Augmented Generation (RAG)
    and model fine-tuning.
  doc_url: https://docs.unstructured.io/welcome
  dev_url: https://github.com/Unstructured-IO/unstructured

extra:
  recipe-maintainers:
    - jan-janssen
