{% set name = "unstructured" %}
{% set version = "0.16.6" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unstructured-{{ version }}.tar.gz
    sha256: b505ae797a32947b11b4eea0d548dfacd7168a8a9f72280cd2df523705a42254
    patches:
      - 0001-use-pytesseract-source.patch
  # tests and tests data files
  - url: https://github.com/Unstructured-IO/unstructured/archive/refs/tags/{{ version }}.tar.gz
    sha256: e55fcee8666fcdc12c5ff60dc3232555191b31d90e575fbf479c07ce3d5a2d72
    folder: gh_src
    patches:
      - 0001-use-pytesseract-gh.patch

build:
  number: 0

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: unstructured
    build:
      # skip py312: langdetect not available
      # skip s390x: deepdiff, httpx, unstructured-client not available
      # skip win: python-magic not available
      skip: true  # [py<39 or py>311 or s390x or win]
      script:
        - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      build:
        - patch
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - chardet
        - filetype
        - python-magic
        - lxml
        - nltk
        - requests
        - beautifulsoup4
        - emoji
        - dataclasses-json
        - python-iso639
        - langdetect
        # NOTE(robinson) - numpy pin is because ONNX model weights are only compatible
        # with numpy 1.x.x
        - numpy <2
        - rapidfuzz
        - backoff
        - typing-extensions
        - unstructured-client >=0.23.0,<0.26.0
        - wrapt >=1.14.0
        - tqdm
        - psutil
        - html5lib
        - python-oxmsg
    test:
      imports:
        - unstructured
      source_files:
        - gh_src/example-docs
        - gh_src/test_unstructured
      requires:
        - python
        - pip
        - pytest
        - pytest-mock
        - pydantic
      commands:
        - pip check
        - cd gh_src
        - pytest -vv test_unstructured/partition/test_text.py -k "not fake-text-utf-16-le"
        - pytest -vv test_unstructured/partition/test_email.py
        - pytest -vv test_unstructured/partition/html/test_partition.py
        - pytest -vv test_unstructured/partition/test_xml.py

  - name: unstructured-ppt
    build:
      skip: true  # [py<39 or py>311 or s390x or win]
      script:
        - {{ PYTHON }} -m pip install -e ".[ppt]" -vv --no-deps --no-build-isolation
    requirements:
      build:
        - patch
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage("unstructured", max_pin="x.x.x", exact=True) }}
        - python-pptx
    test:
      imports:
        - unstructured.partition.ppt
      requires:
        - python
        - pip
      commands:
        - pip check
        # Not running pytest for this package, as it requires libreoffice to be installed
        # https://docs.unstructured.io/open-source/core-functionality/partitioning#partition-ppt

  - name: unstructured-pptx
    build:
      skip: true  # [py<39 or py>311 or s390x or win]
      script:
        - {{ PYTHON }} -m pip install -e ".[pptx]" -vv --no-deps --no-build-isolation
    requirements:
      build:
        - patch
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage("unstructured", max_pin="x.x.x", exact=True) }}
        - python-pptx
    test:
      imports:
        - unstructured.partition.pptx
      source_files:
        - gh_src/example-docs
        - gh_src/test_unstructured
      requires:
        - python
        - pip
        - pytest
        - pytest-mock
      commands:
        - pip check
        - cd gh_src
        # test_it_loads_a_PPTX_with_a_JPEG_misidentified_as_image_jpg requires python-pptx >=1.0.1
        - pytest -vv test_unstructured/partition/test_pptx.py -k "not test_it_loads_a_PPTX_with_a_JPEG_misidentified_as_image_jpg"

  - name: unstructured-pdf
    build:
      skip: true  # [py<39 or py>311 or s390x or win]
      script:
        - {{ PYTHON }} -m pip install -e ".[pdf]" -vv --no-deps --no-build-isolation
    requirements:
      build:
        - patch
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - {{ pin_subpackage("unstructured", max_pin="x.x.x", exact=True) }}
        - onnx
        - pdf2image
        - pdfminer.six
        - pikepdf
        - pi-heif
        - pypdf
        - google-cloud-vision >=2.0.0
        - unstructured-inference 0.8.1.*
        # Lowering the bound from 0.3.12 to 0.3.10 as there are no breaking changes, and tests using pytesseract seem to work
        - pytesseract >=0.3.10
    test:
      imports:
        - unstructured.partition.pdf
      source_files:
        - gh_src/example-docs
        - gh_src/test_unstructured
      requires:
        - python
        - pip
        - pytest
        - pytest-mock
      commands:
        - pip check
        - cd gh_src
        # test_analysis_artifacts_saved requires fonts to be installed on system, not available on CI
        # Testing is unstable on linux-aarch64 CI
        - pytest -vv test_unstructured/partition/pdf_image -k "not (test_analysis_artifacts_saved)"  # [not aarch64]

about:
  home: https://unstructured.io
  license: Apache-2.0
  license_file: LICENSE.md
  license_family: Apache
  summary: A library that prepares raw documents for downstream ML tasks.
  description: |
    Unstructured provides a platform and tools to ingest and process
    unstructured documents for Retrieval Augmented Generation (RAG)
    and model fine-tuning.
  doc_url: https://docs.unstructured.io/welcome
  dev_url: https://github.com/Unstructured-IO/unstructured

extra:
  recipe-maintainers:
    - jan-janssen
  skip-lints:
    - wrong_output_script_key
