{% set name = "unstructured" %}
{% set version = "0.15.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/unstructured-{{ version }}.tar.gz
    sha256: f0f2c83a86d754df79b17f40c01a446c6f38ded4c253d1da1c2c0ec22f6ffc37
    patches:
      - patches/setup.patch
  # tests and tests data files
  - url: https://github.com/Unstructured-IO/unstructured/archive/refs/tags/{{ version }}.tar.gz
    sha256: ed149362cf00e73db4896b2fdb7836b3ebbf2772ff47d81adada27e97973f1b1
    folder: gh_src

build:
  # skip py312: langdetect not available
  # skip s390x: deepdiff, httpx, unstructured-client not available
  # skip win: python-magic not available
  skip: true  # [py<39 or py>311 or s390x or win]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0
  entry_points:
    - unstructured-ingest=unstructured.ingest.main:main

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - chardet
    - filetype
    - python-magic
    - lxml
    - nltk
    - tabulate
    - requests
    - beautifulsoup4
    - emoji
    - dataclasses-json
    - python-iso639
    - langdetect
    # NOTE(robinson) - numpy pin is because ONNX model weights are only compatible
    # with numpy 1.x.x
    - numpy <2
    - rapidfuzz
    - backoff
    - typing-extensions
    - unstructured-client >=0.15.1
    - wrapt >=1.14.0
    - tqdm
    - psutil

{% set tests_to_skip = "" %}
# skip tests that fail on comparing snapshots for utf-16 files formatted differently
{% set tests_to_skip = tests_to_skip + " fake-text-utf-16-le" %}
{% set tests_to_skip = tests_to_skip + " or fake-email-utf-16-le" %}
{% set tests_to_skip = tests_to_skip + " or fake-email-utf-16-be" %}

# See Makefile:: test-no-extras in the Makefile at
# https://github.com/Unstructured-IO/unstructured/blob/main/Makefile#L313-L320
{% set files_to_test = "" %}
{% set files_to_test = files_to_test + "test_unstructured/partition/test_text.py" %}
{% set files_to_test = files_to_test + " test_unstructured/partition/test_email.py" %}
{% set files_to_test = files_to_test + " test_unstructured/partition/test_xml_partition.py" %}
{% set files_to_test = files_to_test + " test_unstructured/partition/html/test_partition.py" %}

test:
  imports:
    - unstructured
  source_files:
    - gh_src/example-docs
    - gh_src/test_unstructured
  requires:
    - pip
    - pytest
    # available and only-used deps in requirements/test.in
    - pytest-mock
    # unstructured-ingest cli
    - pandas
  commands:
    - pip check
    - unstructured-ingest --help
    - cd gh_src
    - pytest -vv {{ files_to_test }} -k "not ({{ tests_to_skip }})"

about:
  home: https://unstructured.io
  license: Apache-2.0
  license_file: LICENSE.md
  license_family: Apache
  summary: A library that prepares raw documents for downstream ML tasks.
  description: |
    Unstructured provides a platform and tools to ingest and process
    unstructured documents for Retrieval Augmented Generation (RAG)
    and model fine-tuning.
  doc_url: https://docs.unstructured.io/welcome
  dev_url: https://github.com/Unstructured-IO/unstructured

extra:
  recipe-maintainers:
    - jan-janssen
